### ISSUE TITLE
Pot discharge - is it safe?

### ISSUE THREAD

**Issue by sorgelig** [daglem/reDIP-SID#9]
Hi!

I don't see any resistor in series for potX/Y, it means when pot is in lower resistivity state (~0 Ohm) with strong 5V drive and FPGA is pulling it down to GND then high current will flow. Isn't it dangerous for FPGA/level-shifter/4066?

**Comment by daglem** [comment]
Good catch!

Checking IBIS files for the FPGA and the bus switch, the current would be in the order of 50mA using normal IO. Even with a 50% duty cycle this probably wouldn't be healthy for neither the 4066 or the FPGA in the long run.

This issue is fixed by using the RGB current drive, as originally planned. See the commit above.
